name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'     # Використовує Temurin замість застарілого Adopt
          cache: maven                # Кешує залежності Maven автоматично

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Auto approve if success
        if: ${{ github.event.pull_request && success() }}
        uses: mate-academy/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto reject if failure
        if: ${{ github.event.pull_request && failure() }}
        uses: mate-academy/auto-reject-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
